  - name: Create a token for {{ GIT_ACCOUNTNAME }}
    ansible.builtin.command: /usr/local/bin/gitea admin user generate-access-token -u {{ GIT_USERNAME }} --scopes all --config /etc/gitea/app.ini | awk '{print $6}'
    #ansible.builtin.command: sudo -u {{ GIT_ACCOUNTNAME }} /usr/local/bin/gitea admin user generate-access-token -u {{ GIT_USERNAME }} --scopes all --config /etc/gitea/app.ini | awk '{print $6}'
    register: USER_TOKEN
    # referenced as USER_TOKEN.stdout
    ignore_errors: true # Ignore this if it's already been created
    become: true
    become_user: "{{ GIT_ACCOUNTNAME }}"

  - name: Check if the token has been saved
    ansible.builtin.stat:
      path: ~/gitea_token.txt
    register: tokenfile

  - name: Write the token so it is accessible
    ansible.builtin.copy:
      content: "{{ USER_TOKEN.stdout }}"
      dest: ~/gitea_token.txt
    when: not tokenfile.stat.exists

  - name: Get just the token
    ansible.builtin.shell: "cat ~/gitea_token.txt | awk '{print $6}'"
    register: JUST_GITEA_USER_TOKEN
    become: true

  - name: Check if the just_token has been saved
    ansible.builtin.stat:
      path: /home/{{ USERNAME }}/just_gitea_token.txt
    register: just_tokenfile

  - name: Write out JUST_GITEA_USER_TOKEN to /home/{{ USERNAME }}/just_gitea_token.txt
    ansible.builtin.copy:
      content: "{{ JUST_GITEA_USER_TOKEN.stdout }}"
      dest: "/home/{{ USERNAME }}/just_gitea_token.txt"
    when: not just_tokenfile.stat.exists




  - name: Make git directory
    ansible.builtin.file:
      state: directory
      path: ~/git
    become: yes
    become_user: "{{ GIT_USERNAME }}"

# Fix This:
#  - name: Clone directories
#    ansible.builtin.command: cd ~/git && curl -X POST 'http://localhost:3000/api/v1/user/repos' -H 'accept: application/json' -H 'Authorization: token {{ USER_TOKEN.stdout }}' -H 'Content-Type: application/json' -d '{\'name\': \'{{ item }}\'}' -i && git clone http://localhost:3000/lab-user/{{ item }}.git
#    with_items: 
#      - "rhel9_soe"
#      - "petclinic"
#      - "rhel10-soe"

 # - name: commit repos
 #   ansible.builtin.command: cd ~/git/{{ item }} && git add . && git commit -m 'Initial commit' && git remote set-url origin http://${GITEA_USER_TOKEN}@localhost:3000/lab-user/{{ item }}.git && git push
 #   with_items:
 #     - "rhel9_soe"
 #     - "petclinic"
 #     - "rhel10-soe"
