- name: Login to registry.redhat.io as user
  containers.podman.podman_login:
    username: "{{ PMUSERNAME }}"
    password: "{{ PMPASSWORD }}"
    registry: registry.redhat.io
  become: true
  become_user: "{{ USERNAME }}"

- name: Pull bootc images
  containers.podman.podman_image:
    name: "{{ item }}"
  with_items:
    - registry.redhat.io/rhel9/rhel-bootc:9.4-1722356971
    - registry.redhat.io/rhel9/rhel-bootc:9.4
    - registry.redhat.io/rhel9/rhel-bootc:latest
  #  - registry.redhat.io/rhel10/rhel-bootc:latest  # Added at the bottom to troubleshoot why this isn't getting pulled
  become: true
  become_user: "{{ USERNAME }}"

- name: Logout of registry.redhat.io as user
  containers.podman.podman_logout:
    registry: registry.redhat.io
  become: true
  become_user: "{{ USERNAME }}"

- name: Login to registry.redhat.io as root
  containers.podman.podman_login:
    username: "{{ PMUSERNAME }}"
    password: "{{ PMPASSWORD }}"
    registry: registry.redhat.io
  become: true

- name: Pull bootc-image-builder
  containers.podman.podman_image:
    name: registry.redhat.io/rhel9/bootc-image-builder:latest
  become: true

- name: Logout of registry.redhat.io as root
  containers.podman.podman_logout:
    registry: registry.redhat.io
  become: true

- name: Login to registry.redhat.io as user
  containers.podman.podman_login:
    username: "{{ PMUSERNAME }}"
    password: "{{ PMPASSWORD }}"
    registry: registry.redhat.io
  become: true
  become_user: "{{ USERNAME }}"

- name: Pull RHEL 10 bootc image
  containers.podman.podman_image:
    name: registry.redhat.io/rhel10/rhel-bootc:latest
  become: true
  become_user: "{{ USERNAME }}"

- name: Logout of registry.redhat.io as user
  containers.podman.podman_logout:
    registry: registry.redhat.io
  become: true
  become_user: "{{ USERNAME }}"