- name: Copy cgi-bin files
  ansible.builtin.copy:
    src: files/nginx/cgi-bin/
    dest: /var/www/cgi-bin
    mode: 0755

- name: Copy php files
  ansible.builtin.copy:
    src: files/nginx/
    dest: "{{ WEB_DIRECTORY }}"

- name: Copy ansible playbooks and files
  ansible.builtin.copy:
    src: files/ansible
    dest: /home/{{ USERNAME }}

- name: Install php-cli so we can access files in cgi-bin
  ansible.builtin.dnf:
    name: php-cli
    state: latest

- name: Enable the cgi boolean for selinux
  ansible.posix.seboolean:
    name: httpd_enable_cgi
    state: true
    persistent: true  

- name: Set file context for /usr/share/nginx/cgi-bin
  ansible.posix.sefcontext:
    target: "/usr/share/nginx/cgi-bin(/.*)?"
    setype: httpd_sys_script_exec_t
    state: present
  with_items:

- name: Set file context for /var/run/fcgiwrap(/.*)?
  ansible.posix.sefcontext:
    target: "/var/run/fcgiwrap(/.*)?"
    setype: httpd_var_run_t
    state: present

- name: Restore file contexts
  ansible.builtin.command: restorecon -R -v /usr/share/nginx/cgi-bin /var/run/fcgiwrap

- name: Enable the fcgiwrap service
  ansible.builtin.systemd_service:
    name: fcgiwrap@nginx.service
    state: started
    enabled: true

- name: Add cgi directory to nginx.conf
  ansible.builtin.blockinfile:
    path: /etc/nginx/nginx.conf
    insertafter: '^ .*location.*50x.html'
    block: |
          }

          location /cgi-bin/ {
                    root /usr/share/nginx;
                    fastcgi_pass unix:/run/fcgiwrap/fcgiwrap-nginx.sock;
                    include fastcgi_params;
                    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

- name: Now restart nginx to pick up changes
  ansible.builtin.systemd_service:
    name: nginx
    state: restarted