- name: Create the petclinic .gitea directory
  ansible.builtin.file:
    path: /home/{{ USERNAME }}/git/petclinic/.gitea/workflows
    state: directory
  when: PREP_WORKFLOW

- name: Copy petclinic files
  ansible.builtin.copy:
    src: /home/{{ USERNAME }}/Workshop/files/
    dest: /home/{{ USERNAME }}/git/petclinic/files/
    remote_src: true
  when: PREP_WORKFLOW

- name: Copy Containerfile9
  ansible.builtin.copy:
    src: /home/{{ USERNAME }}/Workshop/Containerfile-app-RHEL9
    dest: /home/{{ USERNAME }}/git/petclinic/Containerfile9
    remote_src: true
  when: PREP_WORKFLOW

- name: Copy Containerfile10
  ansible.builtin.copy:
    src: /home/{{ USERNAME }}/Workshop/Containerfile-rhel10-app-21
    dest: /home/{{ USERNAME }}/git/petclinic/Containerfile10
    remote_src: true
  when: PREP_WORKFLOW

- name: Copy build_petclinic.yaml
  ansible.builtin.copy:
    src: /home/{{ USERNAME }}/git/petclinic/files/build_petclinic.yaml
    dest: /home/{{ USERNAME }}/git/petclinic/.gitea/workflows/build_petclinic.yaml
    remote_src: true
  when: PREP_WORKFLOW

- name: Set git config
  ansible.builtin.shell: |
    cd /home/{{ USERNAME }}/git/petclinic
    git config --global user.name "lab-user"
    git config --global user.email "lab-user@example.com"
  when: PREP_WORKFLOW #### ADD when it hasn't already been done

- name: Build and push rhel9-soe image
  containers.podman.podman_image:
    name: registry.example.com:5000/rhel9/rhel-bootc:latest
    build:
      file: /home/lab-user/Workshop/Containerfile-new
    pull: false
    push: true
    path: /home/{{ USERNAME }}/Workshop
  when: PREP_WORKFLOW

- name: Build and push rhel10-soe image
  containers.podman.podman_image:
    name: registry.example.com:5000/rhel10/rhel-bootc:latest
    build:
      file: /home/lab-user/Workshop/Containerfile-rhel10-soe
    push: true
    path: /home/{{ USERNAME }}/Workshop
  when: PREP_WORKFLOW

- name: Start the runner
  ansible.builtin.command: /home/{{ USERNAME }}/runner/start_runner.sh
  when: PREP_WORKFLOW 
