- name: Make sure {{USERNAME}} exists
  ansible.builtin.user:
    name: "{{USERNAME}}"
    groups: wheel

- name: Set the users password
  ansible.builtin.shell:
    cmd: usermod -p $(openssl passwd -1 {{USERPASSWORD}}) {{USERNAME}}

- name: Enable Linger
  ansible.builtin.shell:
    cmd: loginctl enable-linger {{USERNAME}}

- name: Add user to libvirtd
  ansible.builtin.shell:
    cmd: usermod -aG libvirt {{USERNAME}}
