- name: Allow http in public zone
  ansible.posix.firewalld:
    service: http
    permanent: true
    state: enabled

- name: Allow http in libvirt zone
  ansible.posix.firewalld:
    service: http
    permanent: true
    state: enabled
    zone: libvirt

- name: Allow https in libvirt zone
  ansible.posix.firewalld:
    service: https
    permanent: true
    state: enabled
    zone: libvirt

- name: Must restart firewall to load rules
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true
    name: firewalld