- name: Create directories in "{{ WEB_DIRECTORY }}/html"
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
  with_items: 
    - "{{ WEB_DIRECTORY }}//html/repo"
    - "{{ WEB_DIRECTORY }}/html/ks"
    - "{{ WEB_DIRECTORY }}/html/rhel9"
    - "{{ WEB_DIRECTORY }}/html/rhel10"
    - "{{ WEB_DIRECTORY }}/html/pxe/rhel9"
    - "{{ WEB_DIRECTORY }}/html/pxe/pxelinux.cfg"
    - "{{ WEB_DIRECTORY }}/html/petclinic"

- name: # Copy everything we need to the webserver
  ansible.builtin.copy:
    src: files/
    dest: "{{ WEB_DIRECTORY }}/html/"

- name: Mount RHEL 9.4 DVD to "{{ WEB_DIRECTORY }}/html/rhel9"
  mount:
    path: "{{ WEB_DIRECTORY }}/html/rhel9"
    src: /mnt/iso/{{ RHEL_9_ISO }}
    fstype: iso9660
    opts: ro
    state: mounted

- name: Mount RHEL 10 DVD to "{{ WEB_DIRECTORY }}/html/rhel10"
  mount:
    path: "{{ WEB_DIRECTORY }}/html/rhel10"
    src: /mnt/iso/{{ RHEL_10_ISO }}
    fstype: iso9660
    opts: ro
    state: mounted

- name: Copy initrd.img and vmlinuz to "{{ WEB_DIRECTORY }}/html/pxe/rhel9"
  ansible.builtin.copy:
    src: "{{ WEB_DIRECTORY }}/html/rhel9/isolinux/"
    dest: "{{ WEB_DIRECTORY }}/html/pxe/rhel9/"
    remote_src: true

- name: Copy the pxe files to "{{ WEB_DIRECTORY }}/html/pxe"
  ansible.builtin.copy:
    src: /tftpboot/
    dest: "{{ WEB_DIRECTORY }}/html/pxe/"
    remote_src: true