---
- name: Configure Gitea for use at demo.redhat.com
  hosts: image_mode
  become: yes
  gather_facts: yes

  vars_files:
    - credentials.yml
    - "{{ playbook_dir }}/roles/prep-environment/defaults/main.yml"

  roles:
    - partition-disk
    - prep-environment
    - create-user
    - download-iso
    - configure-firewall
    - install-registry
    - pull-images
    - {role: user-content, become_user: "{{ USERNAME }}"}
    - web-content
    - prep-workflow
    - install-vscode
    - install-gitea
    - {role: configure-gitea, become_user: "{{ USERNAME}}"}
    - install-novnc
    - install-tigervnc-server
    - {role: git-content, become_user: "{{ USERNAME}}"}
    - install-runner
    - api-simulation
    - display-results