---
- name: Configure Gitea for use at demo.redhat.com
  hosts: localhost
  become: yes
  gather_facts: yes

  vars_files:
    - credentials.yml
      
  roles:
    #- prep-environment
    #- download-iso
    #- configure-firewall
    #- install-registry
    - install-vscode
    - install-gitea
    - {role: configure-gitea, become_user: lab-user}
    - install-novnc
    - install-tigervnc-server
    - {role: git-content, become_user: lab-user}
    - install-runner
    - api-simulation
