---
- name: Configure Gitea for use at demo.redhat.com
  hosts: localhost
  become: yes
  gather_facts: yes

  vars_files:
    - credentials.yml
    - "{{ playbook_dir }}/roles/prep-environment/defaults/main.yml"

  pre_tasks:
    - name: Install required collections
      ansible.builtin.command:
        cmd: ansible-galaxy collection install -r {{ REQUIREMENTS_FILE }}
      args:
        creates: /usr/share/ansible/collections/ansible_collections/community/general
      become: false
      changed_when: false

  roles:
    #- prep-environment
    #- download-iso
    #- configure-firewall
    #- install-registry
    #- pull-images
    #- user-content
    #- web-content
    - install-vscode
    - install-gitea
    - {role: configure-gitea, become_user: "{{ USERNAME}}"}
    - install-novnc
    - install-tigervnc-server
    - {role: git-content, become_user: "{{ USERNAME}}"}
    - install-runner
    - api-simulation